// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU3nr6NFuuWcWFSt4W-rOvh-dMIpB5X_Y',
    appId: '1:247170758217:web:3e845d3041914d79b77198',
    messagingSenderId: '247170758217',
    projectId: 'honeypot-f45ce',
    authDomain: 'honeypot-f45ce.firebaseapp.com',
    storageBucket: 'honeypot-f45ce.firebasestorage.app',
    measurementId: 'G-2DF0R1Q7L1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOtYbjhO3qAHPFFLgXswRwr2TWx5W62QQ',
    appId: '1:247170758217:android:0f64d94c1bb10348b77198',
    messagingSenderId: '247170758217',
    projectId: 'honeypot-f45ce',
    storageBucket: 'honeypot-f45ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYOFEIvghmVM-yuZChB-VNDh1VPbOH2tI',
    appId: '1:247170758217:ios:1b1fbd2e4d4290a1b77198',
    messagingSenderId: '247170758217',
    projectId: 'honeypot-f45ce',
    storageBucket: 'honeypot-f45ce.firebasestorage.app',
    iosBundleId: 'com.example.share2cash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYOFEIvghmVM-yuZChB-VNDh1VPbOH2tI',
    appId: '1:247170758217:ios:1b1fbd2e4d4290a1b77198',
    messagingSenderId: '247170758217',
    projectId: 'honeypot-f45ce',
    storageBucket: 'honeypot-f45ce.firebasestorage.app',
    iosBundleId: 'com.example.share2cash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU3nr6NFuuWcWFSt4W-rOvh-dMIpB5X_Y',
    appId: '1:247170758217:web:dc4ec4090bc560dab77198',
    messagingSenderId: '247170758217',
    projectId: 'honeypot-f45ce',
    authDomain: 'honeypot-f45ce.firebaseapp.com',
    storageBucket: 'honeypot-f45ce.firebasestorage.app',
    measurementId: 'G-TLHXGQ77CJ',
  );
}
